import type { Payment } from "@/handlers/dataTable.config.handler";
import { create } from "zustand";

const tableData: Payment[] = [
    {
        id: "m5gr84i9",
        fileName: "test.txt",
        fileSize: "100 KB",
        fileType: "text/plain",
        testType: "test",
        vehicle: "test",
        step: "test",
        ecu: "test",
        swVersion: "test",
        testName: "test",
        description: "test",
        memoryType: "test",
        user: "test",
        createdAt: new Date(),
        status: "success",
        email: "ken99@example.com",
    },
    {
        id: "m5gr84i9",
        fileName: "test.txt",
        fileSize: "100 KB",
        fileType: "text/plain",
        testType: "test",
        vehicle: "test",
        step: "test",
        ecu: "test",
        swVersion: "test",
        testName: "test",
        description: "test",
        memoryType: "test",
        user: "test",
        createdAt: new Date(),
        status: "success",
        email: "ken99@example.com",
    },
    {
        id: "m5gr84i9",
        fileName: "test.txt",
        fileSize: "100 KB",
        fileType: "text/plain",
        testType: "test",
        vehicle: "test",
        step: "test",
        ecu: "test",
        swVersion: "test",
        testName: "test",
        description: "test",
        memoryType: "test",
        user: "test",
        createdAt: new Date(),
        status: "success",
        email: "ken99@example.com",
    },
    {
        id: "m5gr84i9",
        fileName: "test.txt",
        fileSize: "100 KB",
        fileType: "text/plain",
        testType: "test",
        vehicle: "test",
        step: "test",
        ecu: "test",
        swVersion: "test",
        testName: "test",
        description: "test",
        memoryType: "test",
        user: "test",
        createdAt: new Date(),
        status: "success",
        email: "ken99@example.com",
    },
    {
        id: "m5gr84i9",
        fileName: "test.txt",
        fileSize: "100 KB",
        fileType: "text/plain",
        testType: "test",
        vehicle: "test",
        step: "test",
        ecu: "test",
        swVersion: "test",
        testName: "test",
        description: "test",
        memoryType: "test",
        user: "test",
        createdAt: new Date(),
        status: "success",
        email: "ken99@example.com",
    },
    {
        id: "m5gr84i9",
        fileName: "test.txt",
        fileSize: "100 KB",
        fileType: "text/plain",
        testType: "test",
        vehicle: "test",
        step: "test",
        ecu: "test",
        swVersion: "test",
        testName: "test",
        description: "test",
        memoryType: "test",
        user: "test",
        createdAt: new Date(),
        status: "success",
        email: "ken99@example.com",
    },
    {
        id: "m5gr84i9",
        fileName: "test.txt",
        fileSize: "100 KB",
        fileType: "text/plain",
        testType: "test",
        vehicle: "test",
        step: "test",
        ecu: "test",
        swVersion: "test",
        testName: "test",
        description: "test",
        memoryType: "test",
        user: "test",
        createdAt: new Date(),
        status: "success",
        email: "ken99@example.com",
    },
    {
        id: "m5gr84i9",
        fileName: "test.txt",
        fileSize: "100 KB",
        fileType: "text/plain",
        testType: "test",
        vehicle: "test",
        step: "test",
        ecu: "test",
        swVersion: "test",
        testName: "test",
        description: "test",
        memoryType: "test",
        user: "test",
        createdAt: new Date(),
        status: "success",
        email: "ken99@example.com",
    },
    {
        id: "m5gr84i9",
        fileName: "test.txt",
        fileSize: "100 KB",
        fileType: "text/plain",
        testType: "test",
        vehicle: "test",
        step: "test",
        ecu: "test",
        swVersion: "test",
        testName: "test",
        description: "test",
        memoryType: "test",
        user: "test",
        createdAt: new Date(),
        status: "success",
        email: "ken99@example.com",
    },
    {
        id: "m5gr84i9",
        fileName: "test.txt",
        fileSize: "100 KB",
        fileType: "text/plain",
        testType: "test",
        vehicle: "test",
        step: "test",
        ecu: "test",
        swVersion: "test",
        testName: "test",
        description: "test",
        memoryType: "test",
        user: "test",
        createdAt: new Date(),
        status: "success",
        email: "ken99@example.com",
    },
    {
        id: "m5gr84i9",
        fileName: "test.txt",
        fileSize: "100 KB",
        fileType: "text/plain",
        testType: "test",
        vehicle: "test",
        step: "test",
        ecu: "test",
        swVersion: "test",
        testName: "test",
        description: "test",
        memoryType: "test",
        user: "test",
        createdAt: new Date(),
        status: "success",
        email: "ken99@example.com",
    },
    {
        id: "m5gr84i9",
        fileName: "test.txt",
        fileSize: "100 KB",
        fileType: "text/plain",
        testType: "test",
        vehicle: "test",
        step: "test",
        ecu: "test",
        swVersion: "test",
        testName: "test",
        description: "test",
        memoryType: "test",
        user: "test",
        createdAt: new Date(),
        status: "success",
        email: "ken99@example.com",
    },
    {
        id: "m5gr84i9",
        fileName: "test.txt",
        fileSize: "100 KB",
        fileType: "text/plain",
        testType: "test",
        vehicle: "test",
        step: "test",
        ecu: "test",
        swVersion: "test",
        testName: "test",
        description: "test",
        memoryType: "test",
        user: "test",
        createdAt: new Date(),
        status: "success",
        email: "ken99@example.com",
    },
    {
        id: "m5gr84i9",
        fileName: "test.txt",
        fileSize: "100 KB",
        fileType: "text/plain",
        testType: "test",
        vehicle: "test",
        step: "test",
        ecu: "test",
        swVersion: "test",
        testName: "test",
        description: "test",
        memoryType: "test",
        user: "test",
        createdAt: new Date(),
        status: "success",
        email: "ken99@example.com",
    },
]

interface TableDataStore {
    data: Payment[];
    setData: (data: Payment[]) => void;
}

export const useTableDataStore = create<TableDataStore>((set) => ({
    data: tableData,
    setData: (data) => set({ data }),
}));

