import type { Payment } from "@/handlers/events/dataTable.config.handler";
import { create } from "zustand";
import type { ColDef } from "ag-grid-community";
import { columnDefs, type Column } from "@/handlers/events/dataTable.config.handler";
import { fetchColumns, fetchData } from "@/handlers/services/dataTable.service.handler";

const tableData: Payment[] = [
    {
        id: "m5gr84i9",
        fileName: "test.txt",
        fileSize: "100 KB",
        fileType: "text/plain",
        testType: "test",
        vehicle: "test",
        step: "test",
        ecu: "test",
        swVersion: "test",
        testName: "test",
        description: "test",
        memoryType: "test",
        user: "test",
        createdAt: new Date(),
        status: "success",
        email: "ken99@example.com",
    },
    {
        id: "m5gr84i9",
        fileName: "test.txt",
        fileSize: "100 KB",
        fileType: "text/plain",
        testType: "test",
        vehicle: "test",
        step: "test",
        ecu: "test",
        swVersion: "test",
        testName: "test",
        description: "test",
        memoryType: "test",
        user: "test",
        createdAt: new Date(),
        status: "success",
        email: "ken99@example.com",
    },
    {
        id: "m5gr84i9",
        fileName: "test.txt",
        fileSize: "100 KB",
        fileType: "text/plain",
        testType: "test",
        vehicle: "test",
        step: "test",
        ecu: "test",
        swVersion: "test",
        testName: "test",
        description: "test",
        memoryType: "test",
        user: "test",
        createdAt: new Date(),
        status: "success",
        email: "ken99@example.com",
    },
    {
        id: "m5gr84i9",
        fileName: "test.txt",
        fileSize: "100 KB",
        fileType: "text/plain",
        testType: "test",
        vehicle: "test",
        step: "test",
        ecu: "test",
        swVersion: "test",
        testName: "test",
        description: "test",
        memoryType: "test",
        user: "test",
        createdAt: new Date(),
        status: "success",
        email: "ken99@example.com",
    },
    {
        id: "m5gr84i9",
        fileName: "test.txt",
        fileSize: "100 KB",
        fileType: "text/plain",
        testType: "test",
        vehicle: "test",
        step: "test",
        ecu: "test",
        swVersion: "test",
        testName: "test",
        description: "test",
        memoryType: "test",
        user: "test",
        createdAt: new Date(),
        status: "success",
        email: "ken99@example.com",
    },
    {
        id: "m5gr84i9",
        fileName: "test.txt",
        fileSize: "100 KB",
        fileType: "text/plain",
        testType: "test",
        vehicle: "test",
        step: "test",
        ecu: "test",
        swVersion: "test",
        testName: "test",
        description: "test",
        memoryType: "test",
        user: "test",
        createdAt: new Date(),
        status: "success",
        email: "ken99@example.com",
    },
    {
        id: "m5gr84i9",
        fileName: "test.txt",
        fileSize: "100 KB",
        fileType: "text/plain",
        testType: "test",
        vehicle: "test",
        step: "test",
        ecu: "test",
        swVersion: "test",
        testName: "test",
        description: "test",
        memoryType: "test",
        user: "test",
        createdAt: new Date(),
        status: "success",
        email: "ken99@example.com",
    },
    {
        id: "m5gr84i9",
        fileName: "test.txt",
        fileSize: "100 KB",
        fileType: "text/plain",
        testType: "test",
        vehicle: "test",
        step: "test",
        ecu: "test",
        swVersion: "test",
        testName: "test",
        description: "test",
        memoryType: "test",
        user: "test",
        createdAt: new Date(),
        status: "success",
        email: "ken99@example.com",
    },
    {
        id: "m5gr84i9",
        fileName: "test.txt",
        fileSize: "100 KB",
        fileType: "text/plain",
        testType: "test",
        vehicle: "test",
        step: "test",
        ecu: "test",
        swVersion: "test",
        testName: "test",
        description: "test",
        memoryType: "test",
        user: "test",
        createdAt: new Date(),
        status: "success",
        email: "ken99@example.com",
    },
    {
        id: "m5gr84i9",
        fileName: "test.txt",
        fileSize: "100 KB",
        fileType: "text/plain",
        testType: "test",
        vehicle: "test",
        step: "test",
        ecu: "test",
        swVersion: "test",
        testName: "test",
        description: "test",
        memoryType: "test",
        user: "test",
        createdAt: new Date(),
        status: "success",
        email: "ken99@example.com",
    },
    {
        id: "m5gr84i9",
        fileName: "test.txt",
        fileSize: "100 KB",
        fileType: "text/plain",
        testType: "test",
        vehicle: "test",
        step: "test",
        ecu: "test",
        swVersion: "test",
        testName: "test",
        description: "test",
        memoryType: "test",
        user: "test",
        createdAt: new Date(),
        status: "success",
        email: "ken99@example.com",
    },
    {
        id: "m5gr84i9",
        fileName: "test.txt",
        fileSize: "100 KB",
        fileType: "text/plain",
        testType: "test",
        vehicle: "test",
        step: "test",
        ecu: "test",
        swVersion: "test",
        testName: "test",
        description: "test",
        memoryType: "test",
        user: "test",
        createdAt: new Date(),
        status: "success",
        email: "ken99@example.com",
    },
    {
        id: "m5gr84i9",
        fileName: "test.txt",
        fileSize: "100 KB",
        fileType: "text/plain",
        testType: "test",
        vehicle: "test",
        step: "test",
        ecu: "test",
        swVersion: "test",
        testName: "test",
        description: "test",
        memoryType: "test",
        user: "test",
        createdAt: new Date(),
        status: "success",
        email: "ken99@example.com",
    },
    {
        id: "m5gr84i9",
        fileName: "test.txt",
        fileSize: "100 KB",
        fileType: "text/plain",
        testType: "test",
        vehicle: "test",
        step: "test",
        ecu: "test",
        swVersion: "test",
        testName: "test",
        description: "test",
        memoryType: "test",
        user: "test",
        createdAt: new Date(),
        status: "success",
        email: "ken99@example.com",
    },
]

interface TableDataStore {
    data: Payment[];
    setData: (data: Payment[]) => void;
}

export const useTableDataStore = create<TableDataStore>((set) => ({
    data: tableData,
    setData: (data) => set({ data }),
}));

interface DataTableStore {
    data: any[];
    setData: (data: any[]) => void;
    fetchData: () => Promise<void>;
}

export const useDataTableStore = create<DataTableStore>((set, get) => ({
    data: [],
    setData: (data) => set({ data }),
    fetchData: async () => {
        try {
            const data = await fetchData();
            data.forEach((item) => {
                item.testResult = item.testResult ? "PASS" : "FAIL";
                Object.entries(item.customColumns).forEach(([key, value]) => {
                    item[key] = value;
                });
            });

            get().setData(data);
        } catch (error) {
            console.error('Failed to fetch columns:', error);
        }
    }
}));

